Pg stat statements
CrunchyData/pgmonitor pull request #210
Opened 2020-10-14 20:03 UTC by keithf4

# Description  

pg_stat_statements changed the column names in PG13 in addition to adding new columns. Use consistent method that we handle other situations where different versions of PG have their own query files.

Changed the metric names for pg_stat_statements in versions of PG prior to 13 to just be consistent with the new names in 13. Avoids needing a separate dashboard for different versions of PG and more easily allow the possibility of incorporating those new columns in the future.

## Type of change  
Please check all options that are relevant  
- [x] Bug fix (change which fixes an issue)  
- [ ] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  

**Tested Configuration**:  
- [ ] CentOS, Specify version(s):  CentOS7 
- [ ] PostgreQL, Specify version(s):  11, 13
- [ ] docs tested with hugo <0.60  

Tested with playbook(s):  
# Checklist:  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2020-10-15 13:51 UTC, hunleyd approved these changes

2020-10-20 18:16 UTC, sharmay requested changes

2020-10-20 18:16 UTC, sharmay commented on exporter/postgres/queries_pg_stat_statements_full_pg12.yml
> +                btrim(replace(left(s.query, 40), '\n', '')) AS query,
```suggestion
                left(replace(s.query, '\n', ''),40) AS query,
```

2020-10-21 15:10 UTC, sharmay approved these changes

2020-10-21 15:17 UTC, merged