Add automatic failover alert
CrunchyData/pgmonitor pull request #219
Opened 2020-12-16 17:38 UTC by keithf4

# Description  

Include a default alert rule that can alert on any failover occurrence. 

Fixes (issue) #180 

## Type of change  
Please check all options that are relevant  
- [ ] Bug fix (change which fixes an issue)  
- [x] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  

**Tested Configuration**:  
- [x] CentOS, Specify version(s):  CentOS7
- [x] PostgreQL, Specify version(s):  11
- [ ] docs tested with hugo <0.60  

Tested with playbook(s):  
# Checklist:  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2020-12-17 14:04 UTC, hunleyd requested changes

2020-12-17 14:04 UTC, hunleyd commented on prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example
> +# If a permanent failover alert that requires manual intervention to resolve is required, see the following commented out alert for configuring failover monitoring per named job
```suggestion
# If a permanent failover alert that requires manual intervention to resolve is required, see the commented out alert (beneath this one) for configuring failover monitoring per named job
```

2020-12-18 14:40 UTC, hunleyd requested changes

2020-12-18 14:40 UTC, hunleyd commented on prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example
> +# Monitor for a failover event by watching for the recovery status value to change within specified time period
```suggestion
# Monitor for a failover event by watching for the recovery status value to change within the specified time period
```

2020-12-18 15:18 UTC, pgguru approved these changes

2020-12-21 13:48 UTC, hunleyd requested changes

2020-12-21 13:48 UTC, hunleyd commented on prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example
> +# Monitor for a failover event by watching for the recovery status value to change within the specified time period
```
# Monitor for a failover event by checking if the recovery status value has changed within the specified time period

# IMPORTANT NOTE: This alert will *automatically resolve* after the given offset time period has passed! If you desire to have an alert that must be manually resolved, see the commented out alert beneath this one
```

thoughts?

2020-12-21 14:48 UTC, keithf4 commented on prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example
> +# Monitor for a failover event by watching for the recovery status value to change within the specified time period
I like it. Committed

2020-12-21 16:47 UTC, sharmay approved these changes

2020-12-22 13:22 UTC, hunleyd approved these changes

2020-12-22 13:57 UTC, merged