Add network dashboard
CrunchyData/pgmonitor pull request #221
Opened 2020-12-18 16:28 UTC by keithf4

# Description  

Include a network traffic dashboard in Grafana. 

Would appreciate someone that knows a bit more about what's important to monitoring networks to look over this as well as the network metrics that are provided by node_exporter, to see if it covers the important things

Fixes (issue) #169 

## Type of change  
Please check all options that are relevant  
- [ ] Bug fix (change which fixes an issue)  
- [x] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  

**Tested Configuration**:  
- [ ] CentOS, Specify version(s):  
- [ ] PostgreQL, Specify version(s):  
- [ ] docs tested with hugo <0.60  

Tested with playbook(s):  
# Checklist:  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2020-12-21 13:22 UTC, hunleyd submitted a review, later dismissed

2020-12-21 16:48 UTC, sharmay requested changes

2020-12-21 16:48 UTC, sharmay commented on grafana/Network_Details.json
> +{
Possible to attach screenshot ?

2020-12-21 17:31 UTC, keithf4 commented on grafana/Network_Details.json
> +{
Added screenshots

2020-12-22 22:32 UTC, pgguru submitted a review, later dismissed
I can't speak to the specifics of what are being monitored, but the screenshot looks good and the idea is sound.

2021-02-24 15:01 UTC, hunleyd commented
whats the diff bewtween 'network traffic' and 'network utilization' ?

2021-02-24 16:29 UTC, hunleyd commented
the default metrics on https://github.com/prometheus/node_exporter sound reasonable but don't all appear to be present in the imgs that were attached? 

it looks like this dashboard includes (or can easily include) everything found at https://cdn77.my-netdata.io/#menu_system_submenu_network;theme=slate but seems like we should steal heavily from https://cdn77.my-netdata.io/#menu_ip;theme=slate

2021-02-24 16:44 UTC, keithf4 commented
> whats the diff bewtween 'network traffic' and 'network utilization' ?

Network traffic is based on an irate() of the data using a 3 minute time window to find the difference in the last two values - https://prometheus.io/docs/prometheus/latest/querying/functions/#irate

Traffic utilization is based on an increase() of the data during the last 1 minute - https://prometheus.io/docs/prometheus/latest/querying/functions/#increase

Not sure if this is accurately showing what's intended, hence my request for some assistance on deciding what is useful in this dashboard

2021-03-05 21:20 UTC, pgguru approved these changes

2021-03-08 14:59 UTC, sharmay approved these changes

2021-03-08 15:06 UTC, merged