pgbackrest-info,sh not processing stanza names correctly
CrunchyData/pgmonitor pull request #230
Opened 2021-02-23 23:36 UTC by sharmay

# Description  

1. pgbackrest-info is not handling newline in stanza collection command.
2. BACKREST_STANZAS and BACKREST_CONFIGS uses space delimiter

Fixes (issue) #  

Depends on (issue) #  

## Type of change  
Please check all options that are relevant  
- [x] Bug fix (change which fixes an issue)  
- [ ] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  

**Tested Configuration**:  
- [x] CentOS, Specify version(s):  8
- [X] PostgreQL, Specify version(s):  11
- [ ] docs tested with hugo <0.60  

Tested with playbook(s):  
# Checklist:  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2021-02-24 14:25 UTC, hunleyd approved these changes

2021-02-24 16:07 UTC, keithf4 approved these changes
Tested and working for me with a single config file setup

2021-03-01 15:05 UTC, keithf4 approved these changes
Added dashboards to an existing installation with zero issues.

Tested running the PG11 setup script without any issues.

2021-03-01 19:52 UTC, keithf4 requested changes
When I put the new pgbackrest-info.sh script in place, it starts throwing errors.

With the original script:
```
-bash-4.2$ /usr/bin/pgbackrest-info.sh 
default|[{"archive":[{"database":{"id":1},"id":"11-1","max":"000000010000000000000022","min":"00000001000000000000000C"}],"backup":[{"archive":{"start":"00000001000000000000000C","stop":"00000001000000000000000C"},"backrest":{"format":5,"version":"2.31"},"database":{"id":1},"info":{"delta":33504577,"repository":{"delta":3944636,"size":3944636},"size":33504577},"label":"20210301-184750F","prior":null,"reference":null,"timestamp":{"start":1614624470,"stop":1614624479},"type":"full"}],"cipher":"none","db":[{"id":1,"system-id":6934754275335224956,"version":"11"}],"name":"alpha","status":{"code":0,"lock":{"backup":{"held":false}},"message":"ok"}}]
```
With new script file
```
-bash-4.2$ /usr/bin/pgbackrest-info.sh 
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```
```
-bash-4.2$ cat /etc/pgbackrest.conf
       
###          
#              
# Copyright 2018-2021 Crunchy Data Solutions, Inc. All Rights Reserved.
#                     
###                   
        
[global]   
start-fast=y
log-level-console=info
log-level-file= info
                               
                        
-bash-4.2$ cat /etc/pgbackrest/pgbackrest.conf                                                                                       [9/274]
                         
###
#              
# Copyright 2018-2021 Crunchy Data Solutions, Inc. All Rights Reserved.
#                  
###          

[global]            
start-fast=y 
log-level-console=info
log-level-file= info

-bash-4.2$ cat /etc/pgbackrest/conf.d/alpha.conf

###
#
# Copyright 2018-2021 Crunchy Data Solutions, Inc. All Rights Reserved.
#
###

[alpha]
process-max=3
archive-async=y
spool-path=/var/lib/pgsql/11/spool
repo1-retention-full=1
repo1-retention-diff=1
resume=y
stop-auto=n
compress=y
compress-level=6

pg1-path=/var/lib/pgsql/11/data
pg1-port=5432

repo1-host-user=postgres
repo1-host=192.168.122.15

repo-type=posix

[alpha:archive-get]
process-max=2

[alpha:archive-push]
process-max=2
```

2021-03-02 17:14 UTC, keithf4 commented
> When I put the new pgbackrest-info.sh script in place, it starts throwing errors.
> 

Apologies, forgot to apply the new setup script. Per previous discussion, a more user friendly error with the script that says what value it's expecting would be good.

2021-03-04 15:44 UTC, keithf4 approved these changes

2021-03-08 15:06 UTC, merged