Update Copyright
CrunchyData/pgmonitor pull request #268
Opened 2022-01-04 15:26 UTC by crunchymaggie

# Description  

Update copyright year to 2022

Fixes #  

Depends on #  

## Type of change  
Please check all options that are relevant  
- [ ] Bug fix (change which fixes an issue)  
- [ ] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [x] Documentation update only  

# How Has This Been Tested?  
**Tested Configuration**:  
- [ ] Ansible, Specify version(s):  
- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [ ] docs tested with hugo version(s):  

Tested with playbook(s):  

# Checklist:  
- [ ] My changes generate no new lint warnings  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2022-01-04 15:29 UTC, sharmay commented
@crunchymaggie Missing lot of updates and Duplicate of 267 ?\

2022-01-04 17:44 UTC, hunleyd requested changes

2022-01-04 17:44 UTC, hunleyd commented on LICENSE
> +Copyright 2017-2022 Crunchy Data Solutions, Inc.
all rights reserved?

2022-01-05 15:47 UTC, keithf4 requested changes

2022-01-05 15:47 UTC, keithf4 commented on LICENSE
> +Copyright 2017-2022 Crunchy Data Solutions, Inc.
```suggestion
Copyright 2017-2022 Crunchy Data Solutions, Inc. All Rights Reserved.
```

2022-01-05 22:51 UTC, pgguru commented
Didn't #267 already take care of this?

2022-01-06 14:48 UTC, keithf4 approved these changes

2022-01-06 14:53 UTC, keithf4 commented
> Didn't #267 already take care of this?

Looks like the other PR missed the one this touches

2022-01-06 14:54 UTC, keithf4 commented
> > Didn't #267 already take care of this?
> 
> Looks like the other PR missed the one this touches

Nevermind sorry, was looking at main branch not dev. This was already taken care of

2022-01-06 14:55 UTC, keithf4 commented
Closing this PR since it was taken care of with #267

2022-01-06 14:55 UTC, closed without merging