Monitor for errors reported by pgBackRest
CrunchyData/pgmonitor pull request #284
Opened 2022-05-05 16:06 UTC by keithf4

# Description  

Add a metric to monitor for errors reported by pgBackRest (checksum errors, file truncation, invalid headers, etc). Added alert to monitor for changes in that metric (starts at line 380 in alert file)

This does not monitor for incomplete backup errors. That is already handled by the backrest timing metrics and alerts.

Added some clarification to what is a comment and what are actual alerts in the alert file (double hash for comments)

Fixes #275 

## Type of change  
Please check all options that are relevant  
- [ ] Bug fix (change which fixes an issue)  
- [x] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  
**Tested Configuration**:  
- [x] Ansible, Specify version(s):  2.9
- Installation method:  
    - [ ] Binary install from source, version:  
    - [x] OS package repository, distro, and version:  CentOS7
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [x] PostgreSQL, Specify version(s):  14
- [ ] docs tested with hugo version(s):  

Tested with playbook(s):  

# Checklist:  
- [x] My changes generate no new lint warnings  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2022-05-06 15:02 UTC, hunleyd approved these changes

2022-05-26 20:13 UTC, pgguru requested changes
Minor comment formatting quibble.

2022-05-31 13:41 UTC, hunleyd approved these changes

2022-06-06 20:29 UTC, pgguru approved these changes

2022-07-25 19:51 UTC, merged