Update deprecated storage path variable in prometheus sysconfig
CrunchyData/pgmonitor pull request #298
Opened 2022-10-11 16:07 UTC by keithf4

# Description  

Update the sysconfig file for Prometheus to use non-deprecated value for tsdb storage. Change to clearer `7d` value for retention. Reviewed other options in use by default for prometheus and alertmanager sysconfig and all look fine so far.

Fixes #293 

## Type of change  
Please check all options that are relevant  
- [x] Bug fix (change which fixes an issue)  
- [ ] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  
**Tested Configuration**:  
- [ ] Ansible, Specify version(s):  
- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [ ] docs tested with hugo version(s):  

Tested with playbook(s):  

# Checklist:  
- [ ] My changes generate no new lint warnings  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2022-10-12 12:38 UTC, hunleyd requested changes
changelog fragment?

2022-10-14 14:51 UTC, pgguru submitted a review, later dismissed

2022-10-18 15:18 UTC, hunleyd commented on changelogs/fragments/293.md
> +- sysconfig - update prometheus sysconfig file to use up to date startup values (https://github.com/CrunchyData/pgmonitor/issues/293)
```suggestion
- prometheus - update prometheus sysconfig file to use up to date startup values (https://github.com/CrunchyData/pgmonitor/issues/293)
```

2022-10-19 17:15 UTC, hunleyd approved these changes

2022-10-24 15:27 UTC, pgguru approved these changes

2022-10-24 15:33 UTC, merged