adjusted case statement for ccp_connection_stats to separate out max_query_time
CrunchyData/pgmonitor pull request #318
Opened 2023-01-12 20:29 UTC by cbrianpace

# Description  

*Please fill this template out fully; failure to do so can result in rejection of your PR.*

Please describe the changes made by your PR. This description should be at a high-level but detailed enough that a reviewer understands the scope of the fix or enhancement and can easily judge the PRs validity at addressing the stated issue/feature. Please fully describe any new or changed feature and whether said change is user-facing or not:

A session that is idle in a transaction registers to both max_query_time and max_idle_in_txn_time although it is does not have a long running query but an uncommitted transaction.  Take the two session below (session-1 and session-2).  Executing the session-1 alone causes both metrics to increase even though no pending or active statement is being executed.   This PR will adjust the case statement for max_query_time so that execution of session-1 and session-2 will properly reflect to the actual even metric (session-1 to max_idle_in_txn_time and session-2 to max_query_time).

Session-1:
BEGIN;

Session-2:
select pg_sleep(300);

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [ ] Bugfix
- [ ] Enhancement
- [ ] Breaking Change
- [ ] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #

If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.

depends on #

If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [x] PostgreSQL, Specify version(s):  13, 14, 15
- [ ] docs tested with hugo version(s):  

### Code testing

Have you tested your changes against:
- [ ] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [X] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [X] Ensure that exporter runs with no scrape errors
- [X] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [X] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [X] Not applicable

If your code touches Grafana, have you:
- [ ] Ensured Grafana runs without issue
- [ ] Ensured relevant dashboards load without issue
- [X] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2023-01-13 14:06 UTC, hunleyd submitted a review, later dismissed

2023-01-13 16:40 UTC, pgguru approved these changes

2023-01-18 14:34 UTC, jchancojr submitted a review, later dismissed

2023-01-19 15:34 UTC, keithf4 requested changes
@cbrianpace Can you please resolve the conflicts and merge from development again?

2023-04-12 17:23 UTC, keithf4 commented
> @cbrianpace Can you please resolve the conflicts and merge from development again?

@cbrianpace Just checking in again to see about getting the conflicts in this PR merged. Thanks!

2023-06-16 19:50 UTC, closed without merging