feat: add support for new alertmanager interfaces in grafana
CrunchyData/pgmonitor pull request #365
Opened 2023-09-01 22:27 UTC by keithf4

# Description  

Add support for the new Alertmanager API interface in Grafana. Automatically provisions a new alertmanager and associates that with the Prometheus datasource.

Ran into an issue with the association not working in 9.5 when testing there, but it works in 9.2 :confused: 
https://community.grafana.com/t/prometheus-alertmanager-association-missing-in-9-5/102703

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [ ] Bugfix
- [x] Enhancement
- [ ] Breaking Change
- [ ] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #

If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.

depends on #

If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [x] OS package repository, distro, and version:  Grafana 9.2 from public repo, 9.5 from S3
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [ ] docs tested with hugo version(s):  

### Code testing

Have you tested your changes against:
- [x] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [ ] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [ ] Ensure that exporter runs with no scrape errors
- [x] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [x] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [ ] Not applicable

If your code touches Grafana, have you:
- [ ] Ensured Grafana runs without issue
- [ ] Ensured relevant dashboards load without issue
- [ ] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2023-09-05 12:49 UTC, hunleyd requested changes

2023-09-05 12:49 UTC, hunleyd commented on changelogs/fragments/250.yml
> +  - grafana - update Prometheus Alerts dashboard to include new alert panel interface for active alerts
```suggestion
  - grafana - add Alertmanager datasource to Grafana to allow direct alert management via Grafana
  - grafana - update 'Prometheus Alerts' dashboard to include new alert panel interface for active alerts  
```

2023-09-06 14:13 UTC, hunleyd requested changes

2023-09-06 14:13 UTC, hunleyd commented on hugo/content/grafana/_index.md
> +The extras package takes care of putting all these files in place. If you did not use the crunchy package to install Grafana, see the additional instructions above. Once that is done, the only additi
```suggestion
The extras package takes care of putting all these files in place. If you did not use the Crunchy package to install Grafana, see the additional instructions above. Once that is done, the only additional setup that needs to be done is to set the "provisioning" option in the `grafana.ini` to point to the top level directory if it hasn't been done already. 
```

2023-09-07 13:59 UTC, hunleyd approved these changes

2023-09-15 13:21 UTC, jchancojr approved these changes

2023-09-19 21:06 UTC, pgguru approved these changes

2023-09-20 12:23 UTC, merged