docs: fix recovery metric values in documentation
CrunchyData/pgmonitor pull request #376
Opened 2023-10-10 15:38 UTC by keithf4

# Description  

Fix the recovery metric values in the documentation to be accurate.

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [ ] Bugfix
- [ ] Enhancement
- [ ] Breaking Change
- [x] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #375 

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [x] docs tested with hugo version(s):  0.80.0

### Code testing

Have you tested your changes against:
- [ ] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [ ] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [ ] Not applicable

If your code touches Grafana, have you:
- [ ] Ensured Grafana runs without issue
- [ ] Ensured relevant dashboards load without issue
- [ ] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2023-10-10 15:41 UTC, pgguru submitted a review, later dismissed

2023-10-11 12:53 UTC, hunleyd requested changes
missing fragment?

(the workflow didn't run to catch it)

2023-10-11 13:12 UTC, keithf4 commented
> missing fragment?
> 
> (the workflow didn't run to catch it)



> missing fragment?
> 
> (the workflow didn't run to catch it)

Fixed. Any idea why it didn't run?

2023-10-11 14:31 UTC, hunleyd approved these changes

2023-10-11 15:16 UTC, pgguru approved these changes

2023-10-16 13:06 UTC, jchancojr approved these changes

2023-10-23 13:06 UTC, merged