doc: add guide for upgrading to v5
CrunchyData/pgmonitor pull request #407
Opened 2024-05-14 17:15 UTC by keithf4

# Description  

Add documentation guide for upgrading to v5.

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [ ] Bugfix
- [ ] Enhancement
- [ ] Breaking Change
- [x] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #

If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.

depends on #403 

If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [x] docs tested with hugo version(s):  0.123.8

### Code testing

Have you tested your changes against:
- [ ] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [ ] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [ ] Not applicable

If your code touches Grafana, have you:
- [ ] Ensured Grafana runs without issue
- [ ] Ensured relevant dashboards load without issue
- [ ] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2024-05-15 13:01 UTC, hunleyd requested changes

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +Version 5 of pgMonitor introduces a new exporter that will be used for PostgreSQL. Converting to this new exporter will involve cleaning up the old postgres_exporter, updating Prometheus targets and
```suggestion
Version 5 of pgMonitor introduces a new exporter that will be used for collecting PostgreSQL metrics. Converting to this new exporter will involve cleaning up the old postgres_exporter, updating Prometheus targets, and installing new Grafana dashboards.
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +Note that the pgbouncer_fdw is no longer required to monitor PgBouncer but it still can be used with sql_exporter if desired. If it is not needed, that package can be removed as well. Note that it is
it seems slightly weird to me that we make it this far before actually saying sql_exporter

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +If postgres_exporter was not set up with packages, you can now manually remove all the related files. Note the ## is replaced with the major version of PG that was being monitored. It is possible tha
```suggestion
If postgres_exporter was not set up with packages, you can now manually remove all the related files. Note the ## is replaced with the major version of PG that was being monitored. It is possible that multiple versions of PG had been monitored and copies of these files could exist for all versions. Also, the sysconfig files listed below are the defaults used in examples; there may be additional postgres_exporter sysconfig files on your system(s).
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +All postgres_exporter Prometheus targets can now be removed. If alerting had been set up, they are all likely setting off alarms now that they had been shut down and removed during the previous step.
```suggestion
All postgres_exporter Prometheus targets can now be removed. The default location for Prometheus targets is `/etc/prometheus/auto.d/`, but please check your Prometheus installation for possible additional target locations. In the identified location(s), remove any targets for the postgres_exporter. The default ports for postgres_exporter were 9187 and 9188, so any targets with these ports should be examined for removal. Note that if alerting had previously been enabled, the previous step likely caused multiple alters to fire; once this step is done, you can simply reload Prometheus to clear these targets and any related alerts should resolve themselves. 
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +Any alerts related to postgres_exporter can also be removed from the files contained in the default alert files location `/etc/prometheus/alert-rules.d/`. Note the default original example alert file
```suggestion
Any alerts related to postgres_exporter can also be removed from the files contained in the default alert files location `/etc/prometheus/alert-rules.d/`. Note the default example alert file had been named `crunchy-alert-rules-pg.yml`
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +Version 5.x of pgMonitor ups the minimum required version of Grafana to 10.4. It also removed dashboards related to postgres_exporter and added new ones for sql_exporter. If you are simply using the
```suggestion
Version 5.x of pgMonitor raises the minimum required version of Grafana to 10.4. It also removes dashboards related to postgres_exporter and adds new ones for sql_exporter. If you are simply using the dashboards provided by pgMonitor, the easiest method to update is to simply remove the old ones and install the new ones.
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +If you are using Crunchy packages, simply uninstall the old packages. It's recommended to follow the non-package removal process below as well to ensure things are cleaned up properly.
```suggestion
If you are using Crunchy-provided packages, simply uninstall the old packages. It's recommended to follow the non-package removal process below as well to ensure things are cleaned up properly.
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +If you didn't use the Crunchy packages, ensure the files in the following folder are removed
```suggestion
If you didn't use the Crunchy-provided packages, ensure the files in the following folder are removed:
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +## Setup new sql_exporter
```suggestion
## Set up sql_exporter
```

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +At this point, you should just be able to follow the standard setup instructions for pgMonitor for sql_exporter, Prometheus & Grafana. This will setup the new exporter, Prometheus targets, and new Gr
```suggestion
At this point, ollow the standard setup instructions for pgMonitor for sql_exporter, Prometheus, and Grafana. This will set up sql_exporter, the Prometheus targets, and the new Grafana dashboards.
```
'standard setup instructions' should be a hyperlink to said instructions

2024-05-15 13:01 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
so this isn't an 'upgrade to 5.0' doc; it's a 'convert to sql_exporter' doc, no? if one chooses to stay w/ postgres_exporter in v5 then none of this applies, yes?

2024-05-15 13:51 UTC, keithf4 commented on hugo/content/changelog/v5_upgrade/_index.md
> +All postgres_exporter Prometheus targets can now be removed. If alerting had been set up, they are all likely setting off alarms now that they had been shut down and removed during the previous step.
I would like to have some note in here that the previous step of removing the exporter will likely have set off alerts

2024-05-15 13:58 UTC, keithf4 commented on hugo/content/changelog/v5_upgrade/_index.md
> +Note that the pgbouncer_fdw is no longer required to monitor PgBouncer but it still can be used with sql_exporter if desired. If it is not needed, that package can be removed as well. Note that it is
Will add mention of it to the first sentence above

2024-05-15 14:03 UTC, keithf4 commented on hugo/content/changelog/v5_upgrade/_index.md
postgres_exporter is marked as deprecated. So while you're technically right, I would actually like to leave it with this impression that it's part of moving to 5.0. Yes, they could stay, but they shouldn't.

2024-05-15 14:03 UTC, keithf4 commented on hugo/content/changelog/v5_upgrade/_index.md
> +Note that the pgbouncer_fdw is no longer required to monitor PgBouncer but it still can be used with sql_exporter if desired. If it is not needed, that package can be removed as well. Note that it is
Done

2024-05-15 14:04 UTC, keithf4 commented on hugo/content/changelog/v5_upgrade/_index.md
> +At this point, you should just be able to follow the standard setup instructions for pgMonitor for sql_exporter, Prometheus & Grafana. This will setup the new exporter, Prometheus targets, and new Gr
Link added and reworded a bit

2024-05-16 13:12 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
fair

2024-05-16 13:12 UTC, hunleyd approved these changes, later dismissed

2024-05-16 13:22 UTC, keithf4 commented on hugo/content/changelog/v5_upgrade/_index.md
> +All postgres_exporter Prometheus targets can now be removed. If alerting had been set up, they are all likely setting off alarms now that they had been shut down and removed during the previous step.
@hunleyd Admit the wording on this is a little weak. Any suggestions?

2024-05-23 18:23 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +All postgres_exporter Prometheus targets can now be removed. If alerting had been set up, they are all likely setting off alarms now that they had been shut down and removed during the previous step.
how's that look now @keithf4 ?

2024-05-23 18:24 UTC, jchancojr requested changes

2024-05-23 18:24 UTC, jchancojr commented on hugo/content/changelog/v5_upgrade/_index.md
> +Note that the pgbouncer_fdw is no longer required to monitor PgBouncer but it still can be used with sql_exporter if desired. If it is not needed, that package can be removed as well. Note that it is
```suggestion
Note that the pgbouncer_fdw is no longer required to monitor PgBouncer but it can still be used with sql_exporter if desired. Per previous instructions, it was usually only installed on the global database. The extension can be removed as follows if it's not needed.
```

2024-05-23 18:24 UTC, jchancojr commented on hugo/content/changelog/v5_upgrade/_index.md
> +Note that the pgbouncer_fdw is no longer required to monitor PgBouncer but it still can be used with sql_exporter if desired. If it is not needed, that package can be removed as well. Note that it is
@keithf4

2024-05-23 18:24 UTC, jchancojr commented on hugo/content/_index.md
> +Notes on upgrading can be found in each relevant sections.
```suggestion
Notes on upgrading can be found in each relevant section.
```

2024-05-23 18:24 UTC, jchancojr commented on hugo/content/changelog/v5_upgrade/_index.md
> +This new exporter for PostgreSQL allows for just a single exporter to connect to all databases within a PostgreSQL instance as well as connecting directly to PgBouncer to collect is metrics.
```suggestion
This new exporter for PostgreSQL allows for just a single exporter to connect to all databases within a PostgreSQL instance as well as connecting directly to PgBouncer to collect its metrics.
```

2024-05-24 13:05 UTC, YorviArias submitted a review, later dismissed

2024-05-24 19:20 UTC, jchancojr approved these changes

2024-05-28 14:02 UTC, hunleyd approved these changes

2024-05-28 14:30 UTC, merged