Release notes for version 5.0.0
CrunchyData/pgmonitor pull request #414
Opened 2024-07-09 14:07 UTC by keithf4

# Description  

Update changelogs and release notes for version 5.0.0 release

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [ ] Bugfix
- [ ] Enhancement
- [ ] Breaking Change
- [x] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #

If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.

depends on #

If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [x] docs tested with hugo version(s):  0.123.8

### Code testing

Have you tested your changes against:
- [ ] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [ ] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [ ] Not applicable

If your code touches Grafana, have you:
- [ ] Ensured Grafana runs without issue
- [ ] Ensured relevant dashboards load without issue
- [ ] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2024-07-09 14:10 UTC, hunleyd requested changes

2024-07-09 14:10 UTC, hunleyd commented on hugo/content/changelog/v5_upgrade/_index.md
> +At this point, you should just be able to follow the [standard setup instructions](https://access.crunchydata.com/documentation/pgmonitor/latest/) for the latest version of pgMonitor. This will setup
```suggestion
At this point, you should just be able to follow the [standard setup instructions](https://access.crunchydata.com/documentation/pgmonitor/latest/) for the latest version of pgMonitor. This will set up the new exporter, Prometheus targets, and new Grafana dashboards.
```

2024-07-09 14:10 UTC, hunleyd approved these changes

2024-07-10 16:48 UTC, jchancojr approved these changes

2024-07-10 17:01 UTC, merged