docs: update grafana dashboard and package info. add exporter upgrade…
CrunchyData/pgmonitor pull request #418
Opened 2024-07-22 20:51 UTC by keithf4

… warning

# Description  

Update documentation for new Grafana package organization.

Add a warning about a bad DNF package removal dependency path that can occur depending on the order that packages are installed in. If the Postgresql core package is installed as a dependency of the pgmonitor-pg##-extras package, then when someone goes to remove it, DNF will can potentially think it's an unused dependency when it's then uninstalled later. Using `--noautoremove` for DNF stops that.

 
Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [ ] Bugfix
- [ ] Enhancement
- [ ] Breaking Change
- [x] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #

If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.

depends on #

If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [x] docs tested with hugo version(s):  0.123.8

### Code testing

Have you tested your changes against:
- [ ] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [ ] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [ ] Not applicable

If your code touches Grafana, have you:
- [ ] Ensured Grafana runs without issue
- [ ] Ensured relevant dashboards load without issue
- [ ] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

2024-07-22 21:56 UTC, crunchyjohn reviewed
Easy typo: sql_exporeter -> sql_exporter

2024-07-23 13:45 UTC, keithf4 commented
> Easy typo: sql_exporeter -> sql_exporter

Fixed. Thanks!

2024-07-23 14:19 UTC, hunleyd approved these changes

2024-07-23 14:47 UTC, jchancojr requested changes

2024-07-23 14:47 UTC, jchancojr commented on hugo/content/grafana/_index.md
> +| pgbouncer/direct/PGBouncer.json                              |  PGBouncer (direct) | Provides details from the PgBouncer statistics views when connecting directly to PGBouncer with the sql_exporter
```suggestion
| pgbouncer/direct/PGBouncer.json                              |  PgBouncer (direct) | Provides details from the PgBouncer statistics views when connecting directly to PgBouncer with the sql_exporter. |
```

2024-07-23 14:47 UTC, jchancojr commented on hugo/content/grafana/_index.md
> +| pgbouncer/fdw/PGBouncer.json                                 | PGBouncer | Provides details from the PgBouncer statistics views when using the pgbouncer_fdw. |
```suggestion
| pgbouncer/fdw/PGBouncer.json                                 | PgBouncer | Provides details from the PgBouncer statistics views when using the pgbouncer_fdw. |
```

2024-07-23 15:13 UTC, jchancojr approved these changes

2024-07-23 15:22 UTC, YorviArias approved these changes

2024-07-23 15:28 UTC, merged