Adds pg17 files to postgres_exporter
CrunchyData/pgmonitor pull request #435
Opened 2024-09-19 21:02 UTC by tony-landreth

# Description  

This PR adds pg17 files to help transition off of postgres_exporter.

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [x] Other

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [x] Other:  
- [x] PostgreSQL, Specify version(s): 17 

### Code testing

Have you tested your changes against:
- [x] RedHat/CentOS

If your code touches postgres_exporter, have you:
- [x] Tested against all versions of PostgreSQL affected
- [x] Ensure that exporter runs with no scrape errors

2024-09-20 12:17 UTC, hunleyd requested changes
needs a changelog fragment, otherwise lgtm

2024-09-24 12:45 UTC, hunleyd approved these changes, later dismissed

2024-10-02 20:46 UTC, keithf4 approved these changes

2024-10-03 14:09 UTC, hunleyd approved these changes

2024-10-03 19:00 UTC, jchancojr approved these changes

2024-10-03 20:18 UTC, YorviArias approved these changes

2024-10-04 14:22 UTC, merged